/* autogenerated by Processing revision 1434 on 2026-09-07 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Pong___dev0_0_1 extends PApplet {

float spieler1_x = 20, spieler1_y = 250, spieler2_x = 780, spieler2_y = 250, w_spieler = 20, h_spieler = 100, s_spieler = 6,
ball_x = 400, ball_y = 300, ball_geschwindigkeit_x = -4, ball_geschwindigkeit_y = 0, w_ball = 10, h_ball = 10, p_ball_x = 400, p_ball_y = 300, p_ball_geschwindigkeit_x = -4, p_ball_geschwindigkeit_y = 0,
b_top = 50, b_bottom = 550, faktor = 0.1f;

int punkte1 = 0, punkte2 = 0, frame_width = 800, frame_height = 600, range = 55;

boolean keyW = false, keyS = false, keyUP = false, keyDOWN = false;

public void setup(){
  size(frame_width, frame_height);
  rectMode(CENTER);
}
public void draw(){
  // Setz den Hintergrund auf Schwarz und entfernt die Spieler und den Ball falls vorhanden
  background(0);
  
  // Erschaft die Spielelemente, auf Basis der Wertezuweisungen
  rect(spieler1_x, spieler1_y, w_spieler, h_spieler);
  rect(spieler2_x, spieler2_y, w_spieler, h_spieler);
  rect(ball_x, ball_y, w_ball, h_ball);
  
  // Überprüfung der Eingaben
  if(keyS){
    if(spieler1_y < b_bottom){
      spieler1_y += s_spieler;
    }
  }
  if(keyW){
    if(spieler1_y > b_top){
      spieler1_y -= s_spieler;
    }
  }
  if(keyDOWN){
    if(spieler2_y < b_bottom){
      spieler2_y += s_spieler;
    }
  }
  if(keyUP){
    if(spieler2_y > b_top){
      spieler2_y -= s_spieler;
    }
  }
  
  // Geschwindigkeit wird langsam erhöht
  ball_x = ball_x + ball_geschwindigkeit_x;
  ball_y = ball_y + ball_geschwindigkeit_y;
  
  // Prüfen, ob der Ball die linke Seite erreicht hat
  if(ball_x < 30){
      if(ball_y < (spieler1_y + range) && ball_y > (spieler1_y - range)){
        ball_geschwindigkeit_x = (-ball_geschwindigkeit_x) + 1;
        ball_geschwindigkeit_y = ball_geschwindigkeit_y - (spieler1_y - ball_y) * faktor;
      }
      else{
        punkte2 = punkte2 + 1;
        Score();
      }
  }
  
  // Prüfen, ob der Ball die linke Seite erreicht hat
  if(ball_x > 770){
    if(ball_y < (spieler2_y + range) && ball_y > (spieler2_y - range)){
      ball_geschwindigkeit_x = (-ball_geschwindigkeit_x) + 1;
      ball_geschwindigkeit_y = ball_geschwindigkeit_y - (spieler2_y - ball_y) * faktor;
    }
    else{
      punkte1 = punkte1 + 1;
      Score();
    }
  }
  
  // Kontakt mit der oberen/ unteren Kante
  if(ball_y > 595 || ball_y < 5){
    ball_geschwindigkeit_y = -ball_geschwindigkeit_y;
  }
  
  // Punktestand
  text(punkte1 + " : " + punkte2, 400, 20);
  //text("Ball Position X: " + ball_x + "\nBall Position Y: " + ball_y, 600, 500);
}

// Wenn eine Taste gedrückt ist, wird der Zustand geändert
public void keyPressed(){
  if(key == 'w' || key == 'W') keyW = true;
  if(key == 's' || key == 'S') keyS = true;
  if(keyCode == UP) keyUP = true;
  if(keyCode == DOWN) keyDOWN = true;
}

// Beim loslassen der Taste wird der Zustand auch geändert
public void keyReleased(){
  if(key == 'w' || key == 'W') keyW = false;
  if(key == 's' || key == 'S') keyS = false;
  if(keyCode == UP) keyUP = false;
  if(keyCode == DOWN) keyDOWN = false;
}

// Setzt den Ball zurück nach dem ein Punkt erziehlt wurde
public void Score(){
  ball_x = p_ball_x;
  ball_y = p_ball_y;
  ball_geschwindigkeit_x = p_ball_geschwindigkeit_x;
  ball_geschwindigkeit_y = p_ball_geschwindigkeit_y;
}


  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Pong___dev0_0_1" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
